### ISSUE TITLE
Hay que crear una rama nueva

### ISSUE THREAD

**Issue by HernanPotenza** [lauty2001moreira/TP_SO_i3_7_#1]
Gamma tenés que crear una rama con tu apellido

**Comment by juliansbaglia18** [comment]
Ahi la cree. creo que es asi no?

**Comment by HernanPotenza** [comment]
Y pasanos tu celular así te metemos en un grupo de wpp y es maś fácil hablar jajaja

**Comment by juliansbaglia18** [comment]
dale jajaj 1136201364

**Comment by HernanPotenza** [comment]
Creaste una nueva carpeta/directorio, crear una rama es otra cosa creo
